### PR TITLE
Exit as an error so others programs can catch it

### PR DESCRIPTION
**Pull request by BlivionIaG**
The goal is to be able to catch invalid args as an error in automated scripts and programs.

### CODE REVIEW

**Comment by AlexFlipnote** [comment]
Fair enough

**Comment by BlivionIaG** [comment]
Hi, I'm impressed by the reactivity ^^, quick question, how long until we get it on pip ?

**Comment by AlexFlipnote** [comment]
Can't find comment so just commenting with image for reference.
I've already pushed it to pip, that's why I bumped the version earlier after your merge of PR.

**Comment by BlivionIaG** [comment]
Oh sorry i deleted the comment because it was stupid ^^, someone i know who needed the commit was asking how long until we get it (when i checked earlier it was before you pushed to pip), after i wrote the message i checked and found out it was updated so i deleted the message. My bad ^^

**Comment by AlexFlipnote** [comment]
Ah lol

**Pull request merged**
