### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by KevinZonda**

### CODE REVIEW

**Comment by starmlerp** [comment]
feel like this is going to get closed faster than it was opened when alex sees it

**Comment by KevinZonda** [comment]
> 
> 
> feel like this is going to get closed faster than it was opened when alex sees this

NOT MY FAULT.

**Comment by starmlerp** [comment]
it is kinda your fault tbh

**Comment by Soheab** [comment]
Hmmmm https://joel.net/how-one-guy-ruined-hacktoberfest2020-drama

**Comment by KevinZonda** [comment]
So all you think fixing `|ENGLISH | 简体中文 |` to `| ENGLISH | 简体中文 |` is a mistake???

**Comment by starmlerp** [comment]
first of all, is that even a fix? its not even a grammatical error, and less so even worth a full on pull request, with only a single change, on a repo that never recieved a PR.
second of all, it is very odd for you to open such a small PR at this time of the year, when it is known that hacktober is being spammed by shit pull requests, just for the sake of getting free swag?
this pull request is definitively getting closed

**Comment by KevinZonda** [comment]
> first of all, is that even a fix? its not even a grammatical error, and less so even worth a full on pull request, with only a single change, on a repo that never recieved a PR.
> second of all, it is very odd for you to open such a small PR at this time of the year, when it is known that hacktober is being spammed by shit pull requests, just for the sake of getting free swag?
> this pull request is definitively getting closed

1. In my view, a format wrong is Exactly A WRONG.
1. This point is a little bit hard to understand. What's the relationship between mine and hacktober? What am I for? Free service? You provide it for me?

Exactly, I found this cuz I required a neofetch-like tool. And I found a small wrong, so my correction is a fault? That's it. ALL MY THINGS ARE WRONG, YOU ARE ALL RIGHT! OKAY? ARE U HAPPY???

**Comment by AlexFlipnote** [comment]
Stop arguing. This is a fair PR, my mistake for not having a space when it was for the other language.

**Comment by KevinZonda** [comment]
Thank you :D

**Comment by KevinZonda** [comment]
And apologize for my rude. It's my fault that haven't controlled my mood correctly. :(

**Pull request merged**
